### ISSUE TITLE
图形界面可视化保存的vis_tmp.nii.gz

### ISSUE THREAD

**Issue by Student-HXJ** [ustc-bmec/Whole-Brain-Conv#1]
请问您是用什么工具来可视化保存的vis_tmp.nii.gz的
像论文中展示的那样

**Comment by ustc-bmec** [comment]
可以说得更详细些吗？
是guided back-propagation的步骤？还是后续的处理步骤的工具？

**Comment by Student-HXJ** [comment]
就是sample.ipynb 里给的那个Visualization的例子已经用guided back propagation 处理过了，保存export gradient 为新的nii文件，这个文件应该是用来可是化的吧其实我就是想自己走一遍流程获取到这个图片------------------ 原始邮件 ------------------发件人: ustc-bmec  <notifications@github.com>发送时间: 2019年11月19日 10:15收件人: ustc-bmec/Whole-Brain-Conv <Whole-Brain-Conv@noreply.github.com>抄送: HXJ <hxj_0057@zju.edu.cn>, Author <author@noreply.github.com>主题: 回复：[ustc-bmec/Whole-Brain-Conv] 图形界面可视化保存的vis_tmp.nii.gz (#1)可以说得更详细些吗？
是guided back-propagation的步骤？还是后续的处理步骤的工具？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ustc-bmec/Whole-Brain-Conv/issues/1?email_source=notifications\u0026email_token=AGL3EHQ6F27PYL242NIR2ADQUND5LA5CNFSM4JOJ7BNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEMTKTA#issuecomment-555300172",
"url": "https://github.com/ustc-bmec/Whole-Brain-Conv/issues/1?email_source=notifications\u0026email_token=AGL3EHQ6F27PYL242NIR2ADQUND5LA5CNFSM4JOJ7BNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEMTKTA#issuecomment-555300172",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ustc-bmec** [comment]
代码主要是通过Whole-Brain-Conv/ScriptsForWangEtAl2019/Step3_Plots/Step3.1_allsub_OneForAll_NormSurfCohenD.m实现，具体地是该.m文件中的step1和step2.
要运行以上的代码，除了matlab外，还要安装afni (https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/download_links.html#download-current-precompiled-afni-binaries) 和freesurfer (https://surfer.nmr.mgh.harvard.edu/fswiki/DownloadAndInstall)

**Comment by Student-HXJ** [comment]
王老师，必要的工具我都装好了，但是我好像没有成功运行起来，错误提示是说有一些文件没找到！请问运行step3.1 还需要哪些前提？我能不能只测试一个源task文件nii.gz，比如只选择一个Emotion中的一个fear block来画出这个heatmap激活区域，（这里只使用DNN的heatmap）------------------ 原始邮件 ------------------发件人: ustc-bmec  <notifications@github.com>发送时间: 2019年11月20日 09:32收件人: ustc-bmec/Whole-Brain-Conv <Whole-Brain-Conv@noreply.github.com>抄送: HXJ <hxj_0057@zju.edu.cn>, Author <author@noreply.github.com>主题: 回复：[ustc-bmec/Whole-Brain-Conv] 图形界面可视化保存的vis_tmp.nii.gz (#1)代码主要是通过Whole-Brain-Conv/ScriptsForWangEtAl2019/Step3_Plots/Step3.1_allsub_OneForAll_NormSurfCohenD.m实现，具体地是该.m文件中的step1和step2.
要运行以上的代码，除了matlab外，还要安装afni(https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/download_links.html#download-current-precompiled-afni-binaries)和freesurfer(https://surfer.nmr.mgh.harvard.edu/fswiki/DownloadAndInstall)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ustc-bmec/Whole-Brain-Conv/issues/1?email_source=notifications\u0026email_token=AGL3EHRIPVZNMYOKZVT7CSLQUSHSNA5CNFSM4JOJ7BNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEQL6NI#issuecomment-555794229",
"url": "https://github.com/ustc-bmec/Whole-Brain-Conv/issues/1?email_source=notifications\u0026email_token=AGL3EHRIPVZNMYOKZVT7CSLQUSHSNA5CNFSM4JOJ7BNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEQL6NI#issuecomment-555794229",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ustc-bmec** [comment]
当然可以只处理其中的一些，修改路径和识别的关键词就可以了。
所需要的软件都列出来了的

**Comment by Student-HXJ** [comment]
王老师，请问运行脚本需要用到哪些源文件，sDirmain下放task block文件sDirTmp是放guided BP的输出文件吗那sDirGrads 下放的是什么文件呢还有在allsub_getGradsSurferS4脚本中有一块是check classified right 好像是根据文件名？这里有点疑惑，请问文件名中pred信息是哪一步获取的呢？------------------ 原始邮件 ------------------发件人: ustc-bmec  <notifications@github.com>发送时间: 2019年11月21日 18:57收件人: ustc-bmec/Whole-Brain-Conv <Whole-Brain-Conv@noreply.github.com>抄送: HXJ <hxj_0057@zju.edu.cn>, Author <author@noreply.github.com>主题: 回复：[ustc-bmec/Whole-Brain-Conv] 图形界面可视化保存的vis_tmp.nii.gz (#1)当然可以只处理其中的一些，修改路径和识别的关键词就可以了。
所需要的软件都列出来了的

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ustc-bmec/Whole-Brain-Conv/issues/1?email_source=notifications\u0026email_token=AGL3EHWOYLCXV3OFMYEIICLQUZSSLA5CNFSM4JOJ7BNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEZ2HZQ#issuecomment-557032422",
"url": "https://github.com/ustc-bmec/Whole-Brain-Conv/issues/1?email_source=notifications\u0026email_token=AGL3EHWOYLCXV3OFMYEIICLQUZSSLA5CNFSM4JOJ7BNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEZ2HZQ#issuecomment-557032422",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ustc-bmec** [comment]
sDirGrads 是放可视化出来的nii.gz的，是输入文件夹
tmp是临时文件夹
结果会输出到results和plots里面
right的部分，原来输出的时候就会输出标记正确与否的文件名

里面有些代码是计算从HCP的数据库里的来的统计结果的，跟算法没啥关系，如果你不感兴趣，可以把相应的step注释掉。如果要做，还要再安装一个human connectome workbench（wb_command），以及到HCP的网站上https://db.humanconnectome.org/data/projects/HCP_1200 下载HCP_S1200_997_tfMRI_ALLTASKS_level2_cohensd_hp200_s4_MSMAll.dscalar.nii

**Comment by Student-HXJ** [comment]
请问
```shell
3dcalc -a $file_gradSurf -expr "abs(a)" -prefix AbsGrad.func.gii
VolMax=$(3dmaskave -quiet -max AbsGrad.func.gii)
echo $VolMax
# output the result volume
3dcalc -a $file_gradSurf -expr "100*a/$VolMax" -prefix NormMaxSign_$afx_data
```
这一段代码中， 100*a/$VolMax 是标准化计算吗，
因为我输出的VolMax的值已经在0-1之间了，
```shell
0.14203 0.110936 0.100598 0.105407 0.0631616 0.0620646 0.0510061 0.0118072 0.0101414 0.0140937 0.0375669 0.0338019 0.035051 0.0335435 0.0360524 0.0477757 0.051745 0.0405138 0.0342882 0.0580297 0.0352264 0.0566796 0.0468934 0.0419857 0.0369407 0.0327202 0.0309409
```
这是我一个样本的VolMax输出，请问这个结果正确吗

另外我的系统环境是macos
$VolMax 放在 -expr 后面貌似无法运行......

**Comment by ustc-bmec** [comment]
还是要max一下的，这个输出结果的数量级是对的
是不是mac和linux的""''的用法不一样？我没有用过mac，可能没法给你具体的建议😔
