### ISSUE TITLE
Emotion task parsing problem

### ISSUE THREAD

**Issue by vitruvi** [ustc-bmec/Whole-Brain-Conv#3]
For the emotion task, fear event file ends with a block that starts at 116th sec with 18 sec duration.
""
32.08	18	1
74.223	18	1
116.365	18	1
""

With the 8 sec post-task duration, defined in the hcp labeling script, 116+18+8 sec =142 sec that converts to frame 197. However, there are 175 frames in emotion task file.

How did you handle this situation in your experiment? (the script "ScriptsForWangEtAl2019/Step0_LabelData/Step0.1_HcpCutAndLabelLong" runs into the error below.)

++ 3dTcat: AFNI version=AFNI_19.3.16 (Dec 12 2019) [64-bit]
"** ERROR: selector index 197 is out of range 0..175"

**Comment by ustc-bmec** [comment]
Yes, we had the same problem. So we discarded these blocks at the ending of each run because we've already had large enough samplings.

**Comment by vitruvi** [comment]
thank you for the answer.
